global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'feedback_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['feedback-app:5001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
